/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT4_FTM1CH0SRC_FTM 0x00u /*!<@brief FTM1 channel 0 input capture source select: FTM1_CH0 signal */
#define SOPT4_FTM2CH1SRC_FTM 0x00u /*!<@brief FTM2 channel 1 input capture source select: FTM2_CH1 signal */

/*! @name PORTA4 (number 26), LIFTMOT1_UP
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LIFTMOT1_UP_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LIFTMOT1_UP_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LIFTMOT1_UP_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTA5 (number 27), LIFTMOT1_DOWN
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LIFTMOT1_DOWN_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LIFTMOT1_DOWN_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LIFTMOT1_DOWN_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTA12 (number 28), ULTRA_SONIC_INPUTCAPTURE
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ULTRA_SONIC_INPUTCAPTURE_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ULTRA_SONIC_INPUTCAPTURE_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ULTRA_SONIC_INPUTCAPTURE_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                                          /* @} */

/*! @name PORTA1 (number 23), LIFTMOT2_UP
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LIFTMOT2_UP_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LIFTMOT2_UP_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LIFTMOT2_UP_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTA2 (number 24), LIFTMOT2_DOWN
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LIFTMOT2_DOWN_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LIFTMOT2_DOWN_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LIFTMOT2_DOWN_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTB0 (number 35), ULTRA_SONIC1_SEND
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ULTRA_SONIC1_SEND_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_ULTRA_SONIC1_SEND_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ULTRA_SONIC1_SEND_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ULTRA_SONIC1_SEND_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ULTRA_SONIC1_SEND_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PORTB1 (number 36), ULTRA_SONIC2_SEND
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ULTRA_SONIC2_SEND_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_ULTRA_SONIC2_SEND_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ULTRA_SONIC2_SEND_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ULTRA_SONIC2_SEND_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ULTRA_SONIC2_SEND_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PORTB2 (number 37), STEPMOT_RESET
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_STEPMOT_RESET_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_STEPMOT_RESET_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_STEPMOT_RESET_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_STEPMOT_RESET_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_STEPMOT_RESET_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTB3 (number 38), STEPMOT_MS2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_STEPMOT_MS2_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_STEPMOT_MS2_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_STEPMOT_MS2_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_STEPMOT_MS2_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_STEPMOT_MS2_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTB16 (number 39), STEPMOT_MS1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_STEPMOT_MS1_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_STEPMOT_MS1_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_STEPMOT_MS1_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_STEPMOT_MS1_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_STEPMOT_MS1_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORTB17 (number 40), STEPMOT_MS0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_STEPMOT_MS0_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_STEPMOT_MS0_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_STEPMOT_MS0_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_STEPMOT_MS0_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_STEPMOT_MS0_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORTB18 (number 41), STEPMOT_EN
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_STEPMOT_EN_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_STEPMOT_EN_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_STEPMOT_EN_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_STEPMOT_EN_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_STEPMOT_EN_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTB19 (number 42), STEPMOT_STEP
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_STEPMOT_STEP_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_STEPMOT_STEP_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_STEPMOT_STEP_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTC8 (number 53), STEPMOT_DIR
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_STEPMOT_DIR_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_STEPMOT_DIR_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_STEPMOT_DIR_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_STEPMOT_DIR_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_STEPMOT_DIR_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTC9 (number 54), MOT1_backwards
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MOT1_backwards_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MOT1_backwards_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MOT1_backwards_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTC10 (number 55), MOT1_vorward
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MOT1_vorward_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MOT1_vorward_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MOT1_vorward_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTC11 (number 56), MOT2_backwards
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MOT2_backwards_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MOT2_backwards_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MOT2_backwards_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*! @name PORTD0 (number 57), MOT2_vorward
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MOT2_vorward_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MOT2_vorward_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MOT2_vorward_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORTD1 (number 58), MOT3_backwards
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MOT3_backwards_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MOT3_backwards_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MOT3_backwards_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTD2 (number 59), MOT3_vorward
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MOT3_vorward_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MOT3_vorward_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MOT3_vorward_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORTD4 (number 61), LED_GREEN
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_GREEN_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_GREEN_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_GREEN_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTD5 (number 62), LED_BLUE
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_BLUE_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_BLUE_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_BLUE_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTD3 (number 60), LED_RED
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_RED_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_RED_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_RED_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTD7 (number 64), LEDBARRIER_RIGHT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LEDBARRIER_RIGHT_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LEDBARRIER_RIGHT_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LEDBARRIER_RIGHT_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LEDBARRIER_RIGHT_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LEDBARRIER_RIGHT_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORTE0 (number 1), LEDBARRIER_LEFT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LEDBARRIER_LEFT_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LEDBARRIER_LEFT_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LEDBARRIER_LEFT_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LEDBARRIER_LEFT_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LEDBARRIER_LEFT_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*! @name PORTE1 (number 2), LEDBARRIER_STEPPER
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LEDBARRIER_STEPPER_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LEDBARRIER_STEPPER_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LEDBARRIER_STEPPER_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LEDBARRIER_STEPPER_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LEDBARRIER_STEPPER_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                                   /* @} */

/*! @name PORTA13 (number 29), GROUND_SENSOR
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_GROUND_SENSOR_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_GROUND_SENSOR_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_GROUND_SENSOR_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GROUND_SENSOR_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GROUND_SENSOR_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
