/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v9.0
processor: MK22FN512xxx12
package_id: MK22FN512VLH12
mcu_data: ksdk2_0
processor_version: 9.0.0
pin_labels:
- {pin_num: '26', pin_signal: PTA4/LLWU_P3/FTM0_CH1/NMI_b/EZP_CS_b, label: LIFTMOT1_UP, identifier: LIFTMOT1_up;LIFTMOT1_UP}
- {pin_num: '23', pin_signal: PTA1/UART0_RX/FTM0_CH6/JTAG_TDI/EZP_DI, label: LIFTMOT2_UP, identifier: LIFTMOT1_down;INPUT_CAPTURE_TEST;LIFTMOT2_up;LIFTMOT2_UP}
- {pin_num: '24', pin_signal: PTA2/UART0_TX/FTM0_CH7/JTAG_TDO/TRACE_SWO/EZP_DO, label: LIFTMOT2_DOWN, identifier: LED_BLUE;LIFTMOT2_up;LIFTMOT2_down;LIFTMOT2_DOWN}
- {pin_num: '49', pin_signal: PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/FTM0_CH3/FB_AD11/CMP1_OUT/LPUART0_TX, label: INPUT_CAPTURE_TEST, identifier: UART1_TX;INPUT_CAPTURE_TEST}
- {pin_num: '46', pin_signal: CMP1_IN1/PTC3/LLWU_P7/SPI0_PCS1/UART1_RX/FTM0_CH2/CLKOUT/I2S0_TX_BCLK/LPUART0_RX, label: LIFTMOT1_down, identifier: UART1_RX;LIFTMOT1_down}
- {pin_num: '27', pin_signal: PTA5/USB_CLKIN/FTM0_CH2/I2S0_TX_BCLK/JTAG_TRST_b, label: LIFTMOT1_DOWN, identifier: LIFTMOT1_down;LIFTMOT1_DOWN}
- {pin_num: '28', pin_signal: PTA12/FTM1_CH0/I2S0_TXD0/FTM1_QD_PHA, label: ULTRA_SONIC_INPUTCAPTURE, identifier: STEPMOT_DIR;ULTRA_SONIC_INPUTCAPTURE}
- {pin_num: '29', pin_signal: PTA13/LLWU_P4/FTM1_CH1/I2S0_TX_FS/FTM1_QD_PHB, label: GROUND_SENSOR, identifier: STEPMOT_RESET;ULTRA_SONIC_TIMEBASE;GROUND_SENSOR}
- {pin_num: '35', pin_signal: ADC0_SE8/ADC1_SE8/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/FTM1_QD_PHA, label: ULTRA_SONIC1_SEND, identifier: STEPMOT_MS3;LIFTMOT1_up;ULTRA_SONIC1_SEND}
- {pin_num: '36', pin_signal: ADC0_SE9/ADC1_SE9/PTB1/I2C0_SDA/FTM1_CH1/FTM1_QD_PHB, label: ULTRA_SONIC2_SEND, identifier: STEPMOT_MS2;ULTRA_SONIC2_SEND}
- {pin_num: '39', pin_signal: PTB16/SPI1_SOUT/UART0_RX/FTM_CLKIN0/FB_AD17/EWM_IN, label: STEPMOT_MS1, identifier: STEPMOT_MS1;LEDBARRIER1_up;Stepper_MS2;STEPMOT_MS2}
- {pin_num: '40', pin_signal: PTB17/SPI1_SIN/UART0_TX/FTM_CLKIN1/FB_AD16/EWM_OUT_b, label: STEPMOT_MS0, identifier: STEPMOT_ENABLE;LEDBARRIER1_dwon;STEPMOT_MS1;STEPMOT_MS0}
- {pin_num: '53', pin_signal: ADC1_SE4b/CMP0_IN2/PTC8/FTM3_CH4/I2S0_MCLK/FB_AD7, label: STEPMOT_DIR, identifier: TESTLED;MOT1_vorward;STEPMOT_DIR}
- {pin_num: '54', pin_signal: ADC1_SE5b/CMP0_IN3/PTC9/FTM3_CH5/I2S0_RX_BCLK/FB_AD6/FTM2_FLT0, label: MOT1_backwards, identifier: MOT1_backwords;MOT1_backwards}
- {pin_num: '44', pin_signal: ADC0_SE15/PTC1/LLWU_P6/SPI0_PCS3/UART1_RTS_b/FTM0_CH0/FB_AD13/I2S0_TXD0/LPUART0_RTS_b, label: LIFTMOT1_up, identifier: LIFTMOT1_up}
- {pin_num: '62', pin_signal: ADC0_SE6b/PTD5/SPI0_PCS2/UART0_CTS_b/FTM0_CH5/FB_AD1/EWM_OUT_b/SPI1_SCK, label: LED_BLUE, identifier: LIFTMOT1_down;LED_BLUE}
- {pin_num: '38', pin_signal: ADC0_SE13/PTB3/I2C0_SDA/UART0_CTS_b/FTM0_FLT0, label: STEPMOT_MS2, identifier: LIFTMOT1_up;Stepper_MS3;STEPMOT_MS3;STEPMOT_MS2}
- {pin_num: '61', pin_signal: PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/FB_AD2/EWM_IN/SPI1_PCS0, label: LED_GREEN, identifier: ULTRA_SONIC_TIMEBASE;LED_GREEN}
- {pin_num: '1', pin_signal: ADC1_SE4a/PTE0/CLKOUT32K/SPI1_PCS1/UART1_TX/I2C1_SDA/RTC_CLKOUT, label: LEDBARRIER_LEFT, identifier: ULTRA_SONIC_SEND;LEDBARRIER_LEFT}
- {pin_num: '37', pin_signal: ADC0_SE12/PTB2/I2C0_SCL/UART0_RTS_b/FTM0_FLT3, label: STEPMOT_RESET, identifier: Stepper_RES;STEPMOT_RESET}
- {pin_num: '41', pin_signal: PTB18/FTM2_CH0/I2S0_TX_BCLK/FB_AD15/FTM2_QD_PHA, label: STEPMOT_EN, identifier: STEPMOT_EN}
- {pin_num: '42', pin_signal: PTB19/FTM2_CH1/I2S0_TX_FS/FB_OE_b/FTM2_QD_PHB, label: STEPMOT_STEP, identifier: STEPMOT_STEP}
- {pin_num: '55', pin_signal: ADC1_SE6b/PTC10/I2C1_SCL/FTM3_CH6/I2S0_RX_FS/FB_AD5, label: MOT1_vorward, identifier: MOT1_vorward}
- {pin_num: '56', pin_signal: ADC1_SE7b/PTC11/LLWU_P11/I2C1_SDA/FTM3_CH7/FB_RW_b, label: MOT2_backwards, identifier: MOT2_backwards}
- {pin_num: '57', pin_signal: PTD0/LLWU_P12/SPI0_PCS0/UART2_RTS_b/FTM3_CH0/FB_ALE/FB_CS1_b/FB_TS_b/LPUART0_RTS_b, label: MOT2_vorward, identifier: MOT2_vorward}
- {pin_num: '58', pin_signal: ADC0_SE5b/PTD1/SPI0_SCK/UART2_CTS_b/FTM3_CH1/FB_CS0_b/LPUART0_CTS_b, label: MOT3_backwards, identifier: MOT3_backwards}
- {pin_num: '59', pin_signal: PTD2/LLWU_P13/SPI0_SOUT/UART2_RX/FTM3_CH2/FB_AD4/LPUART0_RX/I2C0_SCL, label: MOT3_vorward, identifier: MOT3_vorward}
- {pin_num: '60', pin_signal: PTD3/SPI0_SIN/UART2_TX/FTM3_CH3/FB_AD3/LPUART0_TX/I2C0_SDA, label: LED_RED, identifier: LED_RED}
- {pin_num: '64', pin_signal: PTD7/UART0_TX/FTM0_CH7/FTM0_FLT1/SPI1_SIN, label: LEDBARRIER_RIGHT, identifier: LEDBARRIER_RIGHT}
- {pin_num: '2', pin_signal: ADC1_SE5a/PTE1/LLWU_P0/SPI1_SOUT/UART1_RX/I2C1_SCL/SPI1_SIN, label: LEDBARRIER_STEPPER, identifier: LEDBARRIER_STEPPER}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '26', peripheral: FTM0, signal: 'CH, 1', pin_signal: PTA4/LLWU_P3/FTM0_CH1/NMI_b/EZP_CS_b, identifier: LIFTMOT1_UP, direction: OUTPUT, pull_select: down,
    pull_enable: disable}
  - {pin_num: '27', peripheral: FTM0, signal: 'CH, 2', pin_signal: PTA5/USB_CLKIN/FTM0_CH2/I2S0_TX_BCLK/JTAG_TRST_b, identifier: LIFTMOT1_DOWN, direction: OUTPUT,
    pull_select: down, pull_enable: disable}
  - {pin_num: '28', peripheral: FTM1, signal: 'CH, 0', pin_signal: PTA12/FTM1_CH0/I2S0_TXD0/FTM1_QD_PHA, identifier: ULTRA_SONIC_INPUTCAPTURE, direction: INPUT, pull_select: down,
    pull_enable: disable}
  - {pin_num: '23', peripheral: FTM0, signal: 'CH, 6', pin_signal: PTA1/UART0_RX/FTM0_CH6/JTAG_TDI/EZP_DI, identifier: LIFTMOT2_UP, direction: OUTPUT, pull_select: down,
    pull_enable: disable}
  - {pin_num: '24', peripheral: FTM0, signal: 'CH, 7', pin_signal: PTA2/UART0_TX/FTM0_CH7/JTAG_TDO/TRACE_SWO/EZP_DO, identifier: LIFTMOT2_DOWN, direction: OUTPUT,
    pull_select: down, pull_enable: disable}
  - {pin_num: '35', peripheral: GPIOB, signal: 'GPIO, 0', pin_signal: ADC0_SE8/ADC1_SE8/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/FTM1_QD_PHA, identifier: ULTRA_SONIC1_SEND,
    direction: OUTPUT}
  - {pin_num: '36', peripheral: GPIOB, signal: 'GPIO, 1', pin_signal: ADC0_SE9/ADC1_SE9/PTB1/I2C0_SDA/FTM1_CH1/FTM1_QD_PHB, identifier: ULTRA_SONIC2_SEND, direction: OUTPUT}
  - {pin_num: '37', peripheral: GPIOB, signal: 'GPIO, 2', pin_signal: ADC0_SE12/PTB2/I2C0_SCL/UART0_RTS_b/FTM0_FLT3, identifier: STEPMOT_RESET, direction: OUTPUT}
  - {pin_num: '38', peripheral: GPIOB, signal: 'GPIO, 3', pin_signal: ADC0_SE13/PTB3/I2C0_SDA/UART0_CTS_b/FTM0_FLT0, identifier: STEPMOT_MS2, direction: OUTPUT}
  - {pin_num: '39', peripheral: GPIOB, signal: 'GPIO, 16', pin_signal: PTB16/SPI1_SOUT/UART0_RX/FTM_CLKIN0/FB_AD17/EWM_IN, identifier: STEPMOT_MS1, direction: OUTPUT}
  - {pin_num: '40', peripheral: GPIOB, signal: 'GPIO, 17', pin_signal: PTB17/SPI1_SIN/UART0_TX/FTM_CLKIN1/FB_AD16/EWM_OUT_b, identifier: STEPMOT_MS0, direction: OUTPUT}
  - {pin_num: '41', peripheral: GPIOB, signal: 'GPIO, 18', pin_signal: PTB18/FTM2_CH0/I2S0_TX_BCLK/FB_AD15/FTM2_QD_PHA, direction: OUTPUT}
  - {pin_num: '42', peripheral: FTM2, signal: 'CH, 1', pin_signal: PTB19/FTM2_CH1/I2S0_TX_FS/FB_OE_b/FTM2_QD_PHB, direction: OUTPUT}
  - {pin_num: '53', peripheral: GPIOC, signal: 'GPIO, 8', pin_signal: ADC1_SE4b/CMP0_IN2/PTC8/FTM3_CH4/I2S0_MCLK/FB_AD7, identifier: STEPMOT_DIR, direction: OUTPUT}
  - {pin_num: '54', peripheral: FTM3, signal: 'CH, 5', pin_signal: ADC1_SE5b/CMP0_IN3/PTC9/FTM3_CH5/I2S0_RX_BCLK/FB_AD6/FTM2_FLT0, identifier: MOT1_backwards, direction: OUTPUT}
  - {pin_num: '55', peripheral: FTM3, signal: 'CH, 6', pin_signal: ADC1_SE6b/PTC10/I2C1_SCL/FTM3_CH6/I2S0_RX_FS/FB_AD5, direction: OUTPUT}
  - {pin_num: '56', peripheral: FTM3, signal: 'CH, 7', pin_signal: ADC1_SE7b/PTC11/LLWU_P11/I2C1_SDA/FTM3_CH7/FB_RW_b, direction: OUTPUT}
  - {pin_num: '57', peripheral: FTM3, signal: 'CH, 0', pin_signal: PTD0/LLWU_P12/SPI0_PCS0/UART2_RTS_b/FTM3_CH0/FB_ALE/FB_CS1_b/FB_TS_b/LPUART0_RTS_b, direction: OUTPUT}
  - {pin_num: '58', peripheral: FTM3, signal: 'CH, 1', pin_signal: ADC0_SE5b/PTD1/SPI0_SCK/UART2_CTS_b/FTM3_CH1/FB_CS0_b/LPUART0_CTS_b, direction: OUTPUT}
  - {pin_num: '59', peripheral: FTM3, signal: 'CH, 2', pin_signal: PTD2/LLWU_P13/SPI0_SOUT/UART2_RX/FTM3_CH2/FB_AD4/LPUART0_RX/I2C0_SCL, direction: OUTPUT}
  - {pin_num: '61', peripheral: FTM0, signal: 'CH, 4', pin_signal: PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/FB_AD2/EWM_IN/SPI1_PCS0, identifier: LED_GREEN, direction: OUTPUT}
  - {pin_num: '62', peripheral: FTM0, signal: 'CH, 5', pin_signal: ADC0_SE6b/PTD5/SPI0_PCS2/UART0_CTS_b/FTM0_CH5/FB_AD1/EWM_OUT_b/SPI1_SCK, identifier: LED_BLUE,
    direction: OUTPUT}
  - {pin_num: '60', peripheral: FTM3, signal: 'CH, 3', pin_signal: PTD3/SPI0_SIN/UART2_TX/FTM3_CH3/FB_AD3/LPUART0_TX/I2C0_SDA, direction: OUTPUT}
  - {pin_num: '64', peripheral: GPIOD, signal: 'GPIO, 7', pin_signal: PTD7/UART0_TX/FTM0_CH7/FTM0_FLT1/SPI1_SIN, direction: INPUT, pull_select: up, pull_enable: enable}
  - {pin_num: '1', peripheral: GPIOE, signal: 'GPIO, 0', pin_signal: ADC1_SE4a/PTE0/CLKOUT32K/SPI1_PCS1/UART1_TX/I2C1_SDA/RTC_CLKOUT, identifier: LEDBARRIER_LEFT,
    direction: INPUT, pull_select: up, pull_enable: enable}
  - {pin_num: '2', peripheral: GPIOE, signal: 'GPIO, 1', pin_signal: ADC1_SE5a/PTE1/LLWU_P0/SPI1_SOUT/UART1_RX/I2C1_SCL/SPI1_SIN, direction: INPUT, pull_select: up,
    pull_enable: enable}
  - {pin_num: '29', peripheral: GPIOA, signal: 'GPIO, 13', pin_signal: PTA13/LLWU_P4/FTM1_CH1/I2S0_TX_FS/FTM1_QD_PHB, identifier: GROUND_SENSOR, direction: INPUT,
    pull_select: up, pull_enable: enable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t GROUND_SENSOR_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA13 (pin 29)  */
    GPIO_PinInit(BOARD_INITPINS_GROUND_SENSOR_GPIO, BOARD_INITPINS_GROUND_SENSOR_PIN, &GROUND_SENSOR_config);

    gpio_pin_config_t ULTRA_SONIC1_SEND_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB0 (pin 35)  */
    GPIO_PinInit(BOARD_INITPINS_ULTRA_SONIC1_SEND_GPIO, BOARD_INITPINS_ULTRA_SONIC1_SEND_PIN, &ULTRA_SONIC1_SEND_config);

    gpio_pin_config_t ULTRA_SONIC2_SEND_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB1 (pin 36)  */
    GPIO_PinInit(BOARD_INITPINS_ULTRA_SONIC2_SEND_GPIO, BOARD_INITPINS_ULTRA_SONIC2_SEND_PIN, &ULTRA_SONIC2_SEND_config);

    gpio_pin_config_t STEPMOT_RESET_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB2 (pin 37)  */
    GPIO_PinInit(BOARD_INITPINS_STEPMOT_RESET_GPIO, BOARD_INITPINS_STEPMOT_RESET_PIN, &STEPMOT_RESET_config);

    gpio_pin_config_t STEPMOT_MS2_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB3 (pin 38)  */
    GPIO_PinInit(BOARD_INITPINS_STEPMOT_MS2_GPIO, BOARD_INITPINS_STEPMOT_MS2_PIN, &STEPMOT_MS2_config);

    gpio_pin_config_t STEPMOT_MS1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB16 (pin 39)  */
    GPIO_PinInit(BOARD_INITPINS_STEPMOT_MS1_GPIO, BOARD_INITPINS_STEPMOT_MS1_PIN, &STEPMOT_MS1_config);

    gpio_pin_config_t STEPMOT_MS0_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB17 (pin 40)  */
    GPIO_PinInit(BOARD_INITPINS_STEPMOT_MS0_GPIO, BOARD_INITPINS_STEPMOT_MS0_PIN, &STEPMOT_MS0_config);

    gpio_pin_config_t STEPMOT_EN_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB18 (pin 41)  */
    GPIO_PinInit(BOARD_INITPINS_STEPMOT_EN_GPIO, BOARD_INITPINS_STEPMOT_EN_PIN, &STEPMOT_EN_config);

    gpio_pin_config_t STEPMOT_DIR_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC8 (pin 53)  */
    GPIO_PinInit(BOARD_INITPINS_STEPMOT_DIR_GPIO, BOARD_INITPINS_STEPMOT_DIR_PIN, &STEPMOT_DIR_config);

    gpio_pin_config_t LEDBARRIER_RIGHT_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD7 (pin 64)  */
    GPIO_PinInit(BOARD_INITPINS_LEDBARRIER_RIGHT_GPIO, BOARD_INITPINS_LEDBARRIER_RIGHT_PIN, &LEDBARRIER_RIGHT_config);

    gpio_pin_config_t LEDBARRIER_LEFT_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE0 (pin 1)  */
    GPIO_PinInit(BOARD_INITPINS_LEDBARRIER_LEFT_GPIO, BOARD_INITPINS_LEDBARRIER_LEFT_PIN, &LEDBARRIER_LEFT_config);

    gpio_pin_config_t LEDBARRIER_STEPPER_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE1 (pin 2)  */
    GPIO_PinInit(BOARD_INITPINS_LEDBARRIER_STEPPER_GPIO, BOARD_INITPINS_LEDBARRIER_STEPPER_PIN, &LEDBARRIER_STEPPER_config);

    /* PORTA1 (pin 23) is configured as FTM0_CH6 */
    PORT_SetPinMux(BOARD_INITPINS_LIFTMOT2_UP_PORT, BOARD_INITPINS_LIFTMOT2_UP_PIN, kPORT_MuxAlt3);

    PORTA->PCR[1] = ((PORTA->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pulldown resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | PORT_PCR_PS(kPORT_PullDown)

                     /* Pull Enable: Internal pullup or pulldown resistor is not enabled on the corresponding pin. */
                     | PORT_PCR_PE(kPORT_PullDisable));

    /* PORTA12 (pin 28) is configured as FTM1_CH0 */
    PORT_SetPinMux(BOARD_INITPINS_ULTRA_SONIC_INPUTCAPTURE_PORT, BOARD_INITPINS_ULTRA_SONIC_INPUTCAPTURE_PIN, kPORT_MuxAlt3);

    PORTA->PCR[12] = ((PORTA->PCR[12] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pulldown resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullDown)

                      /* Pull Enable: Internal pullup or pulldown resistor is not enabled on the corresponding
                       * pin. */
                      | PORT_PCR_PE(kPORT_PullDisable));

    /* PORTA13 (pin 29) is configured as PTA13 */
    PORT_SetPinMux(BOARD_INITPINS_GROUND_SENSOR_PORT, BOARD_INITPINS_GROUND_SENSOR_PIN, kPORT_MuxAsGpio);

    PORTA->PCR[13] = ((PORTA->PCR[13] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTA2 (pin 24) is configured as FTM0_CH7 */
    PORT_SetPinMux(BOARD_INITPINS_LIFTMOT2_DOWN_PORT, BOARD_INITPINS_LIFTMOT2_DOWN_PIN, kPORT_MuxAlt3);

    PORTA->PCR[2] = ((PORTA->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pulldown resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | PORT_PCR_PS(kPORT_PullDown)

                     /* Pull Enable: Internal pullup or pulldown resistor is not enabled on the corresponding pin. */
                     | PORT_PCR_PE(kPORT_PullDisable));

    /* PORTA4 (pin 26) is configured as FTM0_CH1 */
    PORT_SetPinMux(BOARD_INITPINS_LIFTMOT1_UP_PORT, BOARD_INITPINS_LIFTMOT1_UP_PIN, kPORT_MuxAlt3);

    PORTA->PCR[4] = ((PORTA->PCR[4] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pulldown resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | PORT_PCR_PS(kPORT_PullDown)

                     /* Pull Enable: Internal pullup or pulldown resistor is not enabled on the corresponding pin. */
                     | PORT_PCR_PE(kPORT_PullDisable));

    /* PORTA5 (pin 27) is configured as FTM0_CH2 */
    PORT_SetPinMux(BOARD_INITPINS_LIFTMOT1_DOWN_PORT, BOARD_INITPINS_LIFTMOT1_DOWN_PIN, kPORT_MuxAlt3);

    PORTA->PCR[5] = ((PORTA->PCR[5] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pulldown resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | PORT_PCR_PS(kPORT_PullDown)

                     /* Pull Enable: Internal pullup or pulldown resistor is not enabled on the corresponding pin. */
                     | PORT_PCR_PE(kPORT_PullDisable));

    /* PORTB0 (pin 35) is configured as PTB0 */
    PORT_SetPinMux(BOARD_INITPINS_ULTRA_SONIC1_SEND_PORT, BOARD_INITPINS_ULTRA_SONIC1_SEND_PIN, kPORT_MuxAsGpio);

    /* PORTB1 (pin 36) is configured as PTB1 */
    PORT_SetPinMux(BOARD_INITPINS_ULTRA_SONIC2_SEND_PORT, BOARD_INITPINS_ULTRA_SONIC2_SEND_PIN, kPORT_MuxAsGpio);

    /* PORTB16 (pin 39) is configured as PTB16 */
    PORT_SetPinMux(BOARD_INITPINS_STEPMOT_MS1_PORT, BOARD_INITPINS_STEPMOT_MS1_PIN, kPORT_MuxAsGpio);

    /* PORTB17 (pin 40) is configured as PTB17 */
    PORT_SetPinMux(BOARD_INITPINS_STEPMOT_MS0_PORT, BOARD_INITPINS_STEPMOT_MS0_PIN, kPORT_MuxAsGpio);

    /* PORTB18 (pin 41) is configured as PTB18 */
    PORT_SetPinMux(BOARD_INITPINS_STEPMOT_EN_PORT, BOARD_INITPINS_STEPMOT_EN_PIN, kPORT_MuxAsGpio);

    /* PORTB19 (pin 42) is configured as FTM2_CH1 */
    PORT_SetPinMux(BOARD_INITPINS_STEPMOT_STEP_PORT, BOARD_INITPINS_STEPMOT_STEP_PIN, kPORT_MuxAlt3);

    /* PORTB2 (pin 37) is configured as PTB2 */
    PORT_SetPinMux(BOARD_INITPINS_STEPMOT_RESET_PORT, BOARD_INITPINS_STEPMOT_RESET_PIN, kPORT_MuxAsGpio);

    /* PORTB3 (pin 38) is configured as PTB3 */
    PORT_SetPinMux(BOARD_INITPINS_STEPMOT_MS2_PORT, BOARD_INITPINS_STEPMOT_MS2_PIN, kPORT_MuxAsGpio);

    /* PORTC10 (pin 55) is configured as FTM3_CH6 */
    PORT_SetPinMux(BOARD_INITPINS_MOT1_vorward_PORT, BOARD_INITPINS_MOT1_vorward_PIN, kPORT_MuxAlt3);

    /* PORTC11 (pin 56) is configured as FTM3_CH7 */
    PORT_SetPinMux(BOARD_INITPINS_MOT2_backwards_PORT, BOARD_INITPINS_MOT2_backwards_PIN, kPORT_MuxAlt3);

    /* PORTC8 (pin 53) is configured as PTC8 */
    PORT_SetPinMux(BOARD_INITPINS_STEPMOT_DIR_PORT, BOARD_INITPINS_STEPMOT_DIR_PIN, kPORT_MuxAsGpio);

    /* PORTC9 (pin 54) is configured as FTM3_CH5 */
    PORT_SetPinMux(BOARD_INITPINS_MOT1_backwards_PORT, BOARD_INITPINS_MOT1_backwards_PIN, kPORT_MuxAlt3);

    /* PORTD0 (pin 57) is configured as FTM3_CH0 */
    PORT_SetPinMux(BOARD_INITPINS_MOT2_vorward_PORT, BOARD_INITPINS_MOT2_vorward_PIN, kPORT_MuxAlt4);

    /* PORTD1 (pin 58) is configured as FTM3_CH1 */
    PORT_SetPinMux(BOARD_INITPINS_MOT3_backwards_PORT, BOARD_INITPINS_MOT3_backwards_PIN, kPORT_MuxAlt4);

    /* PORTD2 (pin 59) is configured as FTM3_CH2 */
    PORT_SetPinMux(BOARD_INITPINS_MOT3_vorward_PORT, BOARD_INITPINS_MOT3_vorward_PIN, kPORT_MuxAlt4);

    /* PORTD3 (pin 60) is configured as FTM3_CH3 */
    PORT_SetPinMux(BOARD_INITPINS_LED_RED_PORT, BOARD_INITPINS_LED_RED_PIN, kPORT_MuxAlt4);

    /* PORTD4 (pin 61) is configured as FTM0_CH4 */
    PORT_SetPinMux(BOARD_INITPINS_LED_GREEN_PORT, BOARD_INITPINS_LED_GREEN_PIN, kPORT_MuxAlt4);

    /* PORTD5 (pin 62) is configured as FTM0_CH5 */
    PORT_SetPinMux(BOARD_INITPINS_LED_BLUE_PORT, BOARD_INITPINS_LED_BLUE_PIN, kPORT_MuxAlt4);

    /* PORTD7 (pin 64) is configured as PTD7 */
    PORT_SetPinMux(BOARD_INITPINS_LEDBARRIER_RIGHT_PORT, BOARD_INITPINS_LEDBARRIER_RIGHT_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[7] = ((PORTD->PCR[7] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTE0 (pin 1) is configured as PTE0 */
    PORT_SetPinMux(BOARD_INITPINS_LEDBARRIER_LEFT_PORT, BOARD_INITPINS_LEDBARRIER_LEFT_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[0] = ((PORTE->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTE1 (pin 2) is configured as PTE1 */
    PORT_SetPinMux(BOARD_INITPINS_LEDBARRIER_STEPPER_PORT, BOARD_INITPINS_LEDBARRIER_STEPPER_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[1] = ((PORTE->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    SIM->SOPT4 = ((SIM->SOPT4 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT4_FTM1CH0SRC_MASK | SIM_SOPT4_FTM2CH1SRC_MASK)))

                  /* FTM1 channel 0 input capture source select: FTM1_CH0 signal. */
                  | SIM_SOPT4_FTM1CH0SRC(SOPT4_FTM1CH0SRC_FTM)

                  /* FTM2 channel 1 input capture source select: FTM2_CH1 signal. */
                  | SIM_SOPT4_FTM2CH1SRC(SOPT4_FTM2CH1SRC_FTM));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
